### ISSUE TITLE
Add hash for transparent empty PNGs

### ISSUE THREAD

**Issue by mapiworks** [consbio/tpkutils#14]
147ca8bf480d89b17921e24e3c09edcf1cb2228b

**Comment by brendan-ward** [comment]
thanks @mapiworks 

Do you have a small TPK file I could use for testing this addition?

**Comment by brendan-ward** [comment]
resolved by 5dfba9d55a514c4e533ea6cafcf622fd1d029e2e

**Comment by mapiworks** [comment]
The are all huge, sorry.

Also, I found it useful to get the tile root as a user input, see my mod attached.

```
custom_tile_root = input("Layer path [Layers]: ")      
if not custom_tile_root:
   custom_tile_root = "Layers"
```
[__init__.py.zip](https://github.com/consbio/tpkutils/files/926646/__init__.py.zip)

**Comment by brendan-ward** [comment]
@mapiworks I don't want to add `input()` into the internal python API (it isn't entirely CLI at that point), but I am open to having it passed in as a parameter, and making it an option for the CLI.

How did you create a TPK with a file root other than "Layers"?  I'd like to reproduce for a test case.

**Comment by mapiworks** [comment]
They are provided by clients. For my understanding they are using the ARCGIS server.

**Comment by brendan-ward** [comment]
If we can automatically determine the tile root, regardless of name, that would be better than passing that in as a parameter.  Does that seem reasonable to you?

**Comment by mapiworks** [comment]
Yes, absolutely.

**Comment by brendan-ward** [comment]
@mapiworks added support for alternative tile root names in 2391c0d5692618496f5cf35d530760133b6c3fce
