### ISSUE TITLE
Poor performance on large files

### ISSUE THREAD

**Issue by brendan-ward** [consbio/tpkutils#2]
Processing is taking unexpectedly long for a 300 MB file, given that we are mostly just moving bytes around.

Need to profile to determine where we are losing time.

**Comment by nikmolnar** [comment]
This may be related to the sqlite3 inserts. Try wrapping all your inserts in a transaction: http://stackoverflow.com/questions/3852068/sqlite-insert-very-slow

**Comment by brendan-ward** [comment]
Thanks for the hint @nikmolnar !!  It went from hours to a little over a minute when I changed the transaction / journalling settings on the DB.

**Comment by brendan-ward** [comment]
TODO: look into using a generator w/ `executemany` as per example [here](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.executemany)
