### ISSUE TITLE
Export tpk to mbtiles

### ISSUE THREAD

**Issue by ilomon10** [consbio/tpkutils#20]
i try to export tpk to mbtiles but got this following error at line when i call `.to_mbtiles('file_name')` 
`TypeError: 'uri' is an invalid keyword argument for this function`

i run python at Mac OS 10.13.1 High Sierra and Debian 9 and got the same error as above

my code:
```
from tpkutils import TPK

tpk = TPK('file_name.tpk')

tpk.to_mbtiles('output.mbtiles')

tpk.close()
```

**Comment by EdgarJeremy** [comment]
In the readme its clearly says that you need 3.5 version of python.
just to be sure, what version of python do you run your script?

**Comment by brendan-ward** [comment]
Sorry @ilomon10, Python 2.7 is not currently supported.  We are open to it, but have not prioritized doing this work ourselves.
